name: Build and Release APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install NDK
      run: |
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"
        
    - name: Clone Oboe library
      run: |
        git clone https://github.com/google/oboe.git
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Install Android SDK
      run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          echo "y" | sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30" "platform-tools"

    - name: Build APK
      run: |
          flutter config --no-analytics
          flutter doctor -v
          cd $GITHUB_WORKSPACE
          flutter build apk --debug --verbose

        
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: audio-amplifier-apks
        path: |
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Audio Amplifier v1.0.${{ github.run_number }}
        body: |
          Application mobile d'amplification et mixage audio en temps réel
          
          Fonctionnalités:
          - Amplification des sons ambiants avec latence optimisée
          - Interface avec curseur morphing entre 3 modes
          - Algorithmes d'amplification avancés et filtrage actif du bruit
          - Compatible avec écouteurs Bluetooth
          
          Instructions d'installation:
          1. Téléchargez l'APK correspondant à votre appareil
          2. Activez l'installation depuis des sources inconnues
          3. Installez l'application
          4. Accordez les permissions microphone et audio
        files: |
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
